[build]
command = "pnpm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"
TRACKER_SCRIPT_NAME = "t.js"
COLLECT_API_ENDPOINT = "/api/e"
DISABLE_TELEMETRY = "1"

[functions]
included_files = ["node_modules/.geo/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "https://site-metrics-admin.netlify.app/*"
to = "https://metrics.joekirchner.com/:splat"
status = 301
force = true
